version: 1.0.1
name: telegram-todo-service
target: 167.235.224.135
stacks:
  telegram-todo-service:
    containers:
      telegram-todo-service:
        name: telegram-todo-service
        repopath: .
        version: 1.0.7
        path: .
    name: telegram-todo-service
