version: '3.3'

services:
  {{name}}:
    image: {{image}}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{name}}.rule=Host(`{{domain}}`)"
      - "traefik.http.routers.{{name}}.tls.certresolver=myresolver"
      - "traefik.http.services.{{name}}.loadbalancer.server.port=80"
    networks:
      - reverseproxy

networks:
  reverseproxy:
    external:
      name: 'reverseproxy'
